storage_root: storage


data_ingestion:
  root_dir: storage/data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: storage/data_ingestion/data.zip
  unzip_dir: storage/data_ingestion


prepare_base_model:
  root_dir: storage/prepare_base_model
  base_model_path: storage/prepare_base_model/base_model.h5
  updated_base_model_path: storage/prepare_base_model/base_model_updated.h5 



training:
  root_dir: storage/training
  trained_model_path: storage/training/model.h5  

  