storage_root: storage


data_ingestion:
  root_dir: storage/data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: storage/data_ingestion/data.zip
  unzip_dir: storage/data_ingestion